version: '3.7'
services:
    three_body_solver:
      build:
        context: ./ThreeBodyCalculator
        dockerfile: Dockerfile

      image: three_body_solver:latest
      restart: unless-stopped

      deploy:
        mode: replicated
        replicas: 4

      depends_on:
          - database
      ports:
          - '5000:5000'
          
    database: 
      build:
        context: ./Database
        dockerfile: Dockerfile   
      image: database:latest
      ports:
          - '27017:27017'

    visualization:
      build:
        context: ./Visualization
        dockerfile: Dockerfile

      image: visualization:latest
      restart: unless-stopped

      ports:
          - '3000:3000'

      deploy:
        placement:
          constraints: [node.role == manager]

      # network_mode: host



